### ISSUE TITLE
'SubscriptionPeriod' is ambiguous for type lookup in this context - iOS 18.4

### ISSUE THREAD

**Issue by haarj** [RevenueCat/purchases-ios#4937]
Can't compile project.

iOS 18.4
Purchases 5.20.2

`                var unit: SubscriptionPeriod.Unit?
`

**Comment by RCGitBot** [comment]
👀 We've just linked this [issue to our internal tracker](https://revenuecat.zendesk.com/agent/tickets/56014) and notified the team. Thank you for reporting, we're checking this out!

**Comment by fire-at-will** [comment]
Hi @haarj, thanks for reporting! 🙌 

I'm currently not able to reproduce when compiling version 5.20.2 of the SDK using Xcode Version 16.3 (16E140) for iOS 18.4. Would you mind sharing more information about the compilation issue, including the full error from the compiler, the affected file, and affected line number? Additionally, which version of Xcode are you using?

Thanks!

**Comment by haarj** [comment]
Xcode 16.3 (16E140)
I am using the below line of code in my file.
`var unit: SubscriptionPeriod.Unit?
`
Error -> "'SubscriptionPeriod' is ambiguous for type lookup in this context"

I believe Xcode is confused if I am trying to use the class from RevenueCat or the new iOS 18.4 typealias.
`/// Represents the duration of time between subscription renewals.
@available(iOS 18.4, macOS 15.4, tvOS 18.4, watchOS 11.4, visionOS 2.4, *)
public typealias SubscriptionPeriod = Product.SubscriptionPeriod`

**Comment by iamsannyrai** [comment]
Same problem

**Comment by lrochadel** [comment]
I think it is the same problem, too..  
Xcode Version 16.3 (16E140)
IOS 18.4
.../SourcePackages/checkouts/purchases-ios/RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift

'SubscriptionInfo' is ambiguous for type lookup in this context

```
extension SubscriptionInfo: Transaction {

    var type: TransactionType {
        .subscription(isActive: isActive,
                      willRenew: willRenew,
                      expiresDate: expiresDate)
    }

}

```

**Comment by fire-at-will** [comment]
Hi everyone!

@haarj You should be able to resolve the ambiguity in your code by prefixing the class with `RevenueCat`, like so: 

```swift
var unit: RevenueCat.SubscriptionPeriod.Unit?`
```
Let me know if that works for you!

@lrochadel That issue should have been resolved in SDK version [5.18.0](https://github.com/RevenueCat/purchases-ios/releases/tag/5.18.0). Can you try updating to the most recent SDK version (5.20.2) and see if that resolves your issue?

@iamsannyrai Can you ensure that you're on a recent version of purchases-flutter? I believe that specifying  `purchases_flutter ^6.24.0` won't ever update past the 6.X.X series of releases, so you're missing out on the 7.X and current 8.X releases. When updating to the most recent SDK version, please make sure that you upload your in-app purchase key (instructions [here](https://www.revenuecat.com/docs/service-credentials/itunesconnect-app-specific-shared-secret/in-app-purchase-key-configuration)) to make sure that purchases will continue to work with StoreKit 2. 

If that doesn't work, can you please provide more details on the compilation issue, including the full error message, and the affected file/line number?

Thanks y'all! 🙌

**Comment by haarj** [comment]
@fire-at-will you are the best. I'll always take your SubscriptionPeriod over Apple's.

**Comment by lrochadel** [comment]
> (5.20.2) and see if that resolves your issue?

Hi @fire-at-will 
I updated to version 5.20.2, and it worked. Thank you!!

**Comment by fire-at-will** [comment]
@ahmedtanjim Does updating to the most recent Flutter SDK version resolve the issue for you? If not, can you provide the version of the Flutter SDK you're using along with the exact build error, including the file and line number?

Thanks!

**Comment by ahmedtanjim** [comment]
I'm using Flutter version 3.22.2

the error message is 
`
/Users/tanjimahmed/AndroidStudioProjects/dent_shop_manager/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift:96:51: error: 'SubscriptionPeriod' is ambiguous for type lookup in this context
        static func rc_normalized(subscriptionPeriod: SubscriptionPeriod) -> String {
                                                      ^~~~~~~~~~~~~~~~~~
    /Users/tanjimahmed/AndroidStudioProjects/dent_shop_manager/ios/Pods/RevenueCat/Sources/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift:21:20: note: found this candidate
    public final class SubscriptionPeriod: NSObject {
                       ^
    StoreKit.SubscriptionPeriod:2:18: note: found this candidate
    public typealias SubscriptionPeriod = Product.SubscriptionPeriod
                     ^
    /Users/tanjimahmed/AndroidStudioProjects/dent_shop_manager/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift:113:55: error: 'SubscriptionPeriod' is ambiguous for type lookup in this context
        static func rc_normalized(subscriptionPeriodUnit: SubscriptionPeriod.Unit) -> String {
                                                          ^~~~~~~~~~~~~~~~~~
    /Users/tanjimahmed/AndroidStudioProjects/dent_shop_manager/ios/Pods/RevenueCat/Sources/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift:21:20: note: found this candidate
    public final class SubscriptionPeriod: NSObject {
                       ^
    StoreKit.SubscriptionPeriod:2:18: note: found this candidate
    public typealias SubscriptionPeriod = Product.SubscriptionPeriod
                     ^
`

**Comment by ahmedtanjim** [comment]
@fire-at-will Thanks a bunch man, I solved it with the Flutter SDK version 8.5.2, Thanks a lot, I was stuck for a day.
This and other bunch of errors appeared out of nowhere after updating the iOS simulator version to 18.4. i regretted updating it afterward, and there is no workaround that, to build ios you gotta switch to the updated version

**Comment by alextreppass** [comment]
Hi, 

The latest RC Capacitor 9.X SDK https://github.com/RevenueCat/purchases-capacitor compatible with Capacitor 6 doesn't seem to contain the related purchases-ios fix.

We weren't yet planning to update to Capacitor 7 - and are now blocked from building our iOS app due to this. I'll open an issue there and ask if the fix can be back-ported to 9.X cheers

**Comment by iamsannyrai** [comment]
@fire-at-will I had faced the same issue what @ahmedtanjim had faced. But for me even after using the most recent sdk version or specific (8.5.2) doesn't work for me. Not sure if its related with revenuecat or something, with the recent sdk version I am getting following error:

`
.../ios/Pods/gRPC-Core/src/core/lib/promise/detail/basic_seq.h:103:38: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
      103 |                     Traits::template CallSeqFactory(f_, *cur_, std::move(arg)));
          |                                      ^
    1 error generated.
`

with other bunch of warnings

**Comment by ahmedtanjim** [comment]
@iamsannyrai I faced the same problem, increase the Firebase SDK version in podfile, i updated from `  $FirebaseSDKVersion = '10.22.0'
` to `$FirebaseSDKVersion = '11.11.0'`

**Comment by Accessibilly** [comment]
Same problem, I think. Everything worked as recently as a few days ago. For lack of time I can remove RevenueCat from some apps in development, but for one app I can't do that.

Xcode 16.3 (16E140)
iOS 16 minimum deployment

RevenueCat SDK installed using Swift Package Manager.

It looks like I'm on RevenueCat 4.43.4 for iOS. Does that even make sense? I've tried multiple times to update to 5.2 from within Xcode: 

- right click on RevenueCat, select Update Package.
- File | Packages > Update to Latest Package Versions 

I've also tried Reset Package Caches and Resolve Package Versions.

Ambiguity errors are found in PurchasesHelper > PackageExtensions.swift rather than in my code.

![Image](https://github.com/user-attachments/assets/8088a816-0f86-4901-b4eb-590468166e76)

**Comment by haarj** [comment]
@Accessibilly Prefix "SubscriptionPeriod" with "RevenueCat". 
Like so:
`var unit: RevenueCat.SubscriptionPeriod.Unit?`

**Comment by Accessibilly** [comment]
@haarj, do you mean in my code? I tried that in at least one location in my code and it didn't resolve the errors. 

In one project I removed the RevenueCat packages so that I could add them back. Now I'm trying to resolve a different problem. Please see the Edit in my earlier post. In the Choose Package Products, the Add to Target dropdowns for RevenueCat and RevenueCatUI show my target as grayed out.

**Comment by fire-at-will** [comment]
@Accessibilly To migrate from the 4.X to 5.X version of purchases-ios and resolve this issue, you'll likely need to bump your versioning rules in Xcode to allow Swift Package Manager to update you to a new major version of purchases-ios. You can do that by going to your "Package Dependencies" settings for your project, in Xcode, and under "Dependency Rule", select "Up to Next Major Version", and making sure that the number is something like `5.20.3`.

<img width="1946" alt="Image" src="https://github.com/user-attachments/assets/bbf62bec-748d-43c6-aed3-f98178872986" />

Then, click `File | Packages > Update to Latest Package Versions` again to update your SDK version.

When updating from SDK version 4.X to 5.X, please ensure that you've uploaded your in-app purchase key (instructions [here](https://www.revenuecat.com/docs/service-credentials/itunesconnect-app-specific-shared-secret/in-app-purchase-key-configuration)) to ensure that purchasing still works with StoreKit 2, which version 5 of the SDK uses by default.

Thanks!

**Comment by Accessibilly** [comment]
@fire-at-will, thanks! I'll try that again soon. When I tried that change earlier today, shortly after my initial comment, I wasn't able to change the version number for the Dependency Rule for purchases-ios. I'm not sure why I couldn't change the version number, but I'll try that in another iOS project.

**Comment by fire-at-will** [comment]
Hey y'all, since this issue has been resolved, I'm going to go ahead and close out the issue. Feel free to open another issue or reach out to support if you run into any other issues.

Thanks!

**Comment by jonahcashmonkeysolutions** [comment]
**I am getting this error after i think i have upgraded my xcode version**

![Image](https://github.com/user-attachments/assets/54a987fd-3032-4d8e-8bdc-29ea50d1e05e)

📱 Project Type:
	•	Framework: Ionic React + Capacitor
	•	In-App Purchases via: @revenuecat/purchases-capacitor (Capacitor plugin)

**Versions**

RevenueCat SDK (iOS)
**5.20.3 via Swift Package Manager**

**@revenuecat/purchases-capacitor**
9.2.1

**Capacitor Core**
6.0.0

**Xcode**
16.3 (16E140)

**macOS**
15.3.2 (24D81)

🧪 **What I Tried but dint work**
	•	Chnaged RevenueCat to 5.20.3 

![Image](https://github.com/user-attachments/assets/c3c153fd-1a3a-415f-a3a2-8cda9fbdd2a2)

	•	pod install --repo-update
	•	Added the Purchases pod explicitly in Podfile (pod 'Purchases', '5.20.2')
	•	Clean build folder
	•	Reinstalled Pods

**❓ What I’m Trying to Understand:**
	•	Should I still use pod 'Purchases' when I’m already using RevenueCat via SwiftPM?
	•	Do I need to use StoreKit.SubscriptionInfo explicitly to fix this conflict?
	•	Is this a known bug in Capacitor 6 setup with RevenueCat and Xcode 16.3?

**🔍 What’s still happening**

Build still fails with the 'SubscriptionInfo' is ambiguous error in the PurchaseInformation.swift file.

**🙏 Request**

Is there a confirmed version of @revenuecat/purchases-capacitor and the iOS SDK that works without upgrading to Capacitor Core 7, specifically with Capacitor 6 and the latest Xcode?

I can see the new release of revenuecat 

![Image](https://github.com/user-attachments/assets/0782dfe6-bbea-4a26-9f17-dd9f950070f8)

but if i have to upgrade Revenuecat to **version 10.2.3**, i have to upgrade capacitor core to 7 which i am avoiding.

**Comment by MilkBiscuit** [comment]
I meet the same issue on flutter

Flutter 3.30.0-0.1.pre • channel beta • https://github.com/flutter/flutter.git
Tools • Dart 3.8.0 (build 3.8.0-70.0.dev) • DevTools 2.43.0
purchases_flutter: ^8.4.4


How shall I fix this issue exactly???

**Comment by bcmedeiros** [comment]
Same issue on KMP:

```
EmitSwiftModule normal arm64 (in target 'PurchasesHybridCommon' from project 'Pods')
    cd /Users/bruno/git/dealer-product/appIos/Pods
    
/Users/bruno/git/dealer-product/appIos/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift:96:51: error: 'SubscriptionPeriod' is ambiguous for type lookup in this context
    static func rc_normalized(subscriptionPeriod: SubscriptionPeriod) -> String {
                                                  ^~~~~~~~~~~~~~~~~~
/Users/bruno/git/dealer-product/appIos/Pods/RevenueCat/Sources/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift:21:20: note: found this candidate
public final class SubscriptionPeriod: NSObject {
                   ^
StoreKit.SubscriptionPeriod:2:18: note: found this candidate
public typealias SubscriptionPeriod = Product.SubscriptionPeriod
                 ^
/Users/bruno/git/dealer-product/appIos/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift:113:55: error: 'SubscriptionPeriod' is ambiguous for type lookup in this context
    static func rc_normalized(subscriptionPeriodUnit: SubscriptionPeriod.Unit) -> String {
                                                      ^~~~~~~~~~~~~~~~~~
/Users/bruno/git/dealer-product/appIos/Pods/RevenueCat/Sources/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift:21:20: note: found this candidate
public final class SubscriptionPeriod: NSObject {
                   ^
StoreKit.SubscriptionPeriod:2:18: note: found this candidate
public typealias SubscriptionPeriod = Product.SubscriptionPeriod
                 ^

SwiftCompile normal arm64 Compiling\ WinBackOffer+HybridAdditions.swift /Users/bruno/git/dealer-product/appIos/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/WinBackOffer+HybridAdditions.swift (in target 'PurchasesHybridCommon' from project 'Pods')

SwiftCompile normal arm64 /Users/bruno/git/dealer-product/appIos/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/WinBackOffer+HybridAdditions.swift (in target 'PurchasesHybridCommon' from project 'Pods')
    cd /Users/bruno/git/dealer-product/appIos/Pods
    

SwiftCompile normal arm64 Compiling\ CommonFunctionality.swift,\ Constants.swift /Users/bruno/git/dealer-product/appIos/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift /Users/bruno/git/dealer-product/appIos/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/Constants.swift (in target 'PurchasesHybridCommon' from project 'Pods')

SwiftCompile normal arm64 /Users/bruno/git/dealer-product/appIos/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift (in target 'PurchasesHybridCommon' from project 'Pods')
    cd /Users/bruno/git/dealer-product/appIos/Pods
    

SwiftCompile normal arm64 /Users/bruno/git/dealer-product/appIos/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/Constants.swift (in target 'PurchasesHybridCommon' from project 'Pods')
    cd /Users/bruno/git/dealer-product/appIos/Pods
    

SwiftCompile normal arm64 Compiling\ Purchases+HybridAdditions.swift,\ PurchasesAreCompletedBy+HybridAdditions.swift /Users/bruno/git/dealer-product/appIos/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/Purchases+HybridAdditions.swift /Users/bruno/git/dealer-product/appIos/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/PurchasesAreCompletedBy+HybridAdditions.swift (in target 'PurchasesHybridCommon' from project 'Pods')
Command SwiftCompile failed with a nonzero exit code

** BUILD FAILED **


The following build commands failed:
        SwiftEmitModule normal arm64 Emitting\ module\ for\ PurchasesHybridCommon (in target 'PurchasesHybridCommon' from project 'Pods')
        EmitSwiftModule normal arm64 (in target 'PurchasesHybridCommon' from project 'Pods')
        SwiftCompile normal arm64 Compiling\ Purchases+HybridAdditions.swift,\ PurchasesAreCompletedBy+HybridAdditions.swift /Users/bruno/git/dealer-product/appIos/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/Purchases+HybridAdditions.swift /Users/bruno/git/dealer-product/appIos/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/PurchasesAreCompletedBy+HybridAdditions.swift (in target 'PurchasesHybridCommon' from project 'Pods')
        Building project Pods with scheme PurchasesHybridCommon and configuration Debug
(4 failures)
```

**Comment by brandon1525** [comment]
For capacitor and angular projects the fix is update the package PurchasesHybridCommon

`pod update PurchasesHybridCommon`

in my case from PurchasesHybridCommon (13.14.0): to PurchasesHybridCommon (13.26.0): for RevenueCat 5.20.0

**Comment by eli1stark** [comment]
I encountered this problem when I was building an older release with Codemagic. In my `codemagic.yaml`, I had Xcode version set as `latest`. Changing the version to `16.2` solved this issue for me. My version of revenueCat is `purchases_flutter: 8.2.1`

The error I was getting was:

```
Swift Compiler Error (Xcode): 'SubscriptionPeriod' is ambiguous for type lookup in this context
/Users/builder/clone/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift:95:50

Swift Compiler Error (Xcode): 'SubscriptionPeriod' is ambiguous for type lookup in this context
/Users/builder/clone/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift:112:54

Encountered error while archiving for device.
```

**Comment by fabriziocucci** [comment]
Same issue with React Native and `"react-native-purchases": "^7.28.0"` when trying to build on top of Expo SDK 53.

**Comment by MlecznyU** [comment]
Hello, same issue, 

Flutter: 3.22.2 
Purchases: 8.1.0 | 8.8.1 | 9.0.0-beta.1 // tried each of those options
Xcode: 16.3 

Can we open this thread as the issue is still not resolved?

**Comment by AndreSand** [comment]
I had the same issue in Kotlin Multiplatform for the iOS-target.

Solution: Using Swift Package Manager instead of CocoaPods fixed my issue https://www.revenuecat.com/docs/getting-started/installation/kotlin-multiplatform#using-swift-package-manager

**Comment by a0m0rajab** [comment]
Updating to 8.6.2 should solve the issue!
